CREATE TABLE `work_log` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` bigint(11) unsigned NOT NULL COMMENT '用户id',
  `log_date` date NOT NULL COMMENT '日期',
  `state` tinyint(4) NOT NULL COMMENT '日志状态0仅保存,1已上报,2已查阅,3已退回,4已审阅',
  `report_date` datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '上报时间',
  `organ_id` bigint(20) unsigned NOT NULL COMMENT '机构id',
  `depart_id` bigint(20) unsigned NOT NULL COMMENT '科室id',
  `official_depart_id` bigint(20) unsigned NOT NULL COMMENT '三定科室id',
  `cost_time` decimal(6,1) unsigned NOT NULL COMMENT '时长:单位小时',
  `un_audit_ids` varchar(100) NOT NULL DEFAULT '' COMMENT '未审阅人id串',
  `audited_ids` varchar(100) NOT NULL DEFAULT '' COMMENT '已审阅人id串',
  `plan_ids` varchar(100) NOT NULL DEFAULT '' COMMENT '日志计划id串',
  `return_memo` varchar(50) NOT NULL DEFAULT '' COMMENT '退回说明',
  `term_type` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT '填报终端类型0电脑端1安卓手机2苹果手机',
  `gmt_create` datetime(6) NOT NULL DEFAULT current_timestamp(6) COMMENT '创建时间',
  `gmt_modified` datetime(6) NOT NULL DEFAULT '1900-01-01 00:00:00.000000' ON UPDATE current_timestamp(6) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_log_user_date` (`user_id`,`log_date`),
  KEY `idx_organ_date` (`organ_id`,`log_date`),
  KEY `idx_depart_date` (`depart_id`,`log_date`),
  KEY `idx_date_organ` (`log_date`,`organ_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1160662 DEFAULT CHARSET=utf8 COMMENT='业务_工作日志';